name: rider linting

on: push

jobs:
  check-format:
    runs-on: windows-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1

      - name: Install resharper global tools
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools

      - name: Check out code
        uses: actions/checkout@v2
      - run: echo ${{ github.workspace }}/unity-rider-linting.sln
      - name: Run rider inspect
        run: jb inspectcode ${{ github.workspace }}/unity-rider-linting.sln --output=inspect-log.text --format=text --no-swea --severity=WARNING --verbosity=ERROR --no-build
